### PR TITLE
fix:ttf could not found error

### PR DESCRIPTION
**Pull request by godcong**
fix:
https://github.com/GoAdminGroup/themes/issues/2
https://github.com/GoAdminGroup/go-admin/issues/117

### CODE REVIEW

**Comment by godcong** [comment]
other way is copy the `6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDc.ttf` into `/resource/assets/dist/css/fonts`

**Comment by godcong** [comment]
you must rebuild it...
`adminlte` and `sword` has two Makefile
compiling it is simple

**Comment by godcong** [comment]
i changed the font to `6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdr.ttf`
then `make all`.
it can works

**Comment by godcong** [comment]
no one check...

**Comment by chenhg5** [comment]
> no one check...

Sorry for reply late, I think it was fixed in the previous commits, however, thanks for your pr.

**Comment by godcong** [comment]
> > no one check...
> 
> Sorry for reply late, I think it was fixed in the previous commits, however, thanks for your pr.

Just fix it, that's fine

**Pull request closed without merging**
